name: eduforge_ai
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/fonts/
      - assets/fonts/Satoshi_Complete/
      - assets/fonts/Satoshi_Complete/Fonts/
      - assets/fonts/Satoshi_Complete/Fonts/OTF/
      - assets/fonts/Satoshi_Complete/Fonts/TTF/
      - assets/fonts/Satoshi_Complete/Fonts/WEB/
      - assets/fonts/Satoshi_Complete/Fonts/WEB/css/
      - assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/
      - assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Regular.woff2
      - assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Bold.woff2
      - assets/fonts/Satoshi_Complete/License/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Regular.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Bold.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Light.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Medium.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Black.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-Italic.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-BoldItalic.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-LightItalic.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-MediumItalic.woff2
        - asset: assets/fonts/Satoshi_Complete/Fonts/WEB/fonts/Satoshi-BlackItalic.woff2
          style: italic
        - asset: assets/fonts/Satoshi_Complete/Fonts/TTF/Satoshi-Variable.ttf
          weight: 400