// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwiS5IDk2jg_7uRcfH9wXp6YI4FKwWc0',
    appId: '1:565567142688:web:c7b47f70b5d4987ec7f545',
    messagingSenderId: '565567142688',
    projectId: 'eduforge-ai-dc572',
    authDomain: 'eduforge-ai-dc572.firebaseapp.com',
    storageBucket: 'eduforge-ai-dc572.firebasestorage.app',
    measurementId: 'G-87W47T5YMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2sXLkuO-oC29AruRGl_83g6mMCO8jEa0',
    appId: '1:565567142688:android:95eaa2b4b26f24d2c7f545',
    messagingSenderId: '565567142688',
    projectId: 'eduforge-ai-dc572',
    storageBucket: 'eduforge-ai-dc572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFppwomiPni5sbytc0ExIEGOnn2Kh8TKA',
    appId: '1:565567142688:ios:095da5ce85f7d337c7f545',
    messagingSenderId: '565567142688',
    projectId: 'eduforge-ai-dc572',
    storageBucket: 'eduforge-ai-dc572.firebasestorage.app',
    iosBundleId: 'com.example.eduforgeAi',
  );
}
